{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restapi-flask.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: api.localhost.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "restapi-flask.fullname" . }}
            port:
              number: {{ .Values.appPort | default 5000 }}
{{ end }}